# fly.toml app configuration file generated for combine-rss-as-api-rough-shape-1568 on 2024-03-20T22:30:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'combine-rss-as-api-rough-shape-1568'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
